[project]
name = "flac_bitstream"
version = "0.1.0"
authors = [
    { name = "nu774", email = "honeycomb77@gmail.com" }
]
description = "bitstream based on libFLAC implementation"
license = {text = "BSD"}

[build-system]
requires = ["setuptools", "wheel", "cython>=3.0.10"]
